version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13-browsers

    branches:
      only:
        - master

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: git reset --hard HEAD
      - run: npm install && npm run build-angular
      - run: git config user.email "${GITHUB_EMAIL}"
      - run: git config user.name "${GITHUB_USERNAME}"
      - run: git add ./
      - run: git commit -m 'record lighthouse'
      - run: git push origin master

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
